function S = grdc_attribute_schema(shortCode)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%GRDC_ATTRIBUTE_SCHEMA Shared GRDC-Caravan catchment-attribute schema.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    shortCode = upper(char(string(shortCode)));
    S.name = ['GRDC-Caravan ' shortCode ' attributes'];
    files = { ...
        'attributes_other_grdc.csv', ...
        'attributes_caravan_grdc.csv', ...
        'attributes_hydroatlas_grdc.csv', ...
        'attributes_additional_grdc.csv'};
    S.tables = repmat(struct('file','','keys',{{}}, ...
        'make_valid_names',true),numel(files),1);
    for i = 1:numel(files)
        S.tables(i).file = files{i};
        S.tables(i).keys = {'gauge_id','gaugeid','station_id'};
    end
    S.id.column = 'gauge_id';
    S.id.uppercase = true;
    S.id.strip = true;
    S.id.regex = {'^GRDC[_-]',''; '\.0+$',''};
    S.metadata.name_sources = {'gauge_name','station_name','name'};
    S.metadata.name_transform = 'title_case';
    S.region = ['CAMELS_' shortCode];
    S.zone.region = shortCode;
    definitions = { ...
        'gauge_lat',{'gauge_lat','gauge_latitude','lat','latitude'},true; ...
        'gauge_lon',{'gauge_lon','gauge_longitude','lon','longitude'},true; ...
        'area',{'area','area_km2','catchment_area','area_calc'},true; ...
        'p_mean',{'p_mean','precipitation_mean'},false; ...
        'pet_mean_fao_pm',{'pet_mean_fao_pm','pet_mean_FAO_PM', ...
            'potential_evaporation_mean_fao_pm'},false; ...
        'aridity_fao_pm',{'aridity_fao_pm','aridity_FAO_PM','aridity'},false; ...
        'p_seasonality',{'seasonality_FAO_PM','p_seasonality', ...
            'precipitation_seasonality'},false; ...
        'frac_snow',{'frac_snow','fraction_snow'},false; ...
        'high_prec_freq',{'high_prec_freq'},false; ...
        'high_prec_dur',{'high_prec_dur'},false; ...
        'low_prec_freq',{'low_prec_freq'},false; ...
        'low_prec_dur',{'low_prec_dur'},false};
    S.aliases = repmat(struct('target','','sources',{{}}, ...
        'required',false,'default',NaN),size(definitions,1),1);
    for i = 1:size(definitions,1)
        S.aliases(i).target = definitions{i,1};
        S.aliases(i).sources = definitions{i,2};
        S.aliases(i).required = definitions{i,3};
    end
    S.progress.label = ['... Reading ' shortCode ...
        ' GRDC-Caravan generic attributes'];
end
