function generate_publication_exports()
%GENERATE_PUBLICATION_EXPORTS Build the runnable Project 3--5 sources.
% These scripts deliberately use the same training pipeline as the GUI
% exporter, while basin selection is repeated from the publication split
% file so the sources do not embed thousands of prepared-basin values.

repo = fileparts(fileparts(fileparts(mfilename('fullpath'))));
template = fileread(fullfile(repo,'examples','run_SAGE_export_hymod.m'));
marker = '%% Initialize SAGEhydrology';
start = strfind(template,marker);
assert(~isempty(start),'The canonical SAGE export template is unavailable.');
tail = template(start(1):end);
old = ['% Select and order attributes for prepared basins ' newline ...
    'A = select_basin_attributes(A_reg,ID,bas.id_gauge);' newline ...
    '% Get spatial coordinates of basins ' newline ...
    'latlon = get_latlon(dirD,bas);'];
new = ['% Select publication basins and reproduce their stored split ' newline ...
    '[A,bas,latlon] = sample_basins(A_reg,ID,bas,prd, ...' newline ...
    '    gname,zone,dirD,file_univ,file_split);'];
tail = strrep(tail,old,new);

spec = project_specs(repo);
for k = 1:numel(spec)
    body = [header_text(spec(k)) configuration_text(spec(k)) tail];
    body = strrep(body,'write_header(mdl) ', ...
        header_call(spec(k)));
    body = strrep(body, ...
        ['mdl.crr_backend = misc.crr_backend; ' ...
        '% Keep training and postprocessing synchronized'], ...
        ['mdl.crr_backend = misc.crr_backend; ' ...
        '% Keep training and' newline ...
        '    % postprocessing synchronized']);
    body = strrep(body, ...
        ['C.runtime = struct(''lastIter'',i,''timing'',struct(''data'',' ...
        'prf.wallT_data,''initialization'',prf.wallT_init,''training'',' ...
        'prf.wallT_train,''information'',prf.wallT_info,''postprocessing'',' ...
        'prf.wallT_post,''gui'',prf.wallT_gui,''total'',prf.wallT_total));'], ...
        ['C.runtime = struct(''lastIter'',i,''timing'',struct( ...' newline ...
        '    ''data'',prf.wallT_data, ...' newline ...
        '    ''initialization'',prf.wallT_init, ...' newline ...
        '    ''training'',prf.wallT_train, ...' newline ...
        '    ''information'',prf.wallT_info, ...' newline ...
        '    ''postprocessing'',prf.wallT_post, ...' newline ...
        '    ''gui'',prf.wallT_gui,''total'',prf.wallT_total));']);
    fid = fopen(spec(k).output,'w','n','UTF-8');
    assert(fid >= 0,'Cannot write project source: %s',spec(k).output);
    cleaner = onCleanup(@() fclose(fid));
    fwrite(fid,body,'char');
    clear cleaner
end
end

function spec = project_specs(repo)
common = struct('repo',repo,'model',1,'K',0,'Kt',0,'Ke',0, ...
    'dt',1,'region','','regionName','','dataRoot','', ...
    'meteoPath','','qPath','','fileUniverse','','fileSplit','', ...
    'trainStart',[],'trainEnd',[],'evalStart',[],'evalEnd',[], ...
    'meteoData',1,'observed','{''Q''}','weights','', ...
    'project','','name','','title','','summary','','output','', ...
    'modelName','','resolution','','dataType','Discharge', ...
    'lossName','Generalized Least Squares', ...
    'optimizerName','Adam/AdamW', ...
    'headerLiteral','');

spec(1) = common;
spec(1).project = 'Project 3';
spec(1).name = 'CAMELS-US hourly';
spec(1).modelName = 'hymod';
spec(1).resolution = 'Hourly';
spec(1).title = ['Hourly Large-Sample Hydrologic Modeling with SAGE: ' ...
    'Performance, Regionalization, and Parameter Transfer across ' ...
    'Temporal Scales'];
spec(1).summary = ['Hourly CAMELS-US experiment using NLDAS forcing and ' ...
    'the prescribed 400/99 split of 499 publication basins.'];
spec(1).region = 'CAMELS_US';
spec(1).regionName = 'United States (CAMELS)';
spec(1).dataRoot = 'CAMELS_US';
spec(1).meteoPath = fullfile('hourly','forcing');
spec(1).qPath = fullfile('hourly','streamflow');
spec(1).fileUniverse = 'US_499_basins.txt';
spec(1).fileSplit = 'split_US_499_400_99_1.txt';
spec(1).K = 499; spec(1).Kt = 400; spec(1).Ke = 99;
spec(1).dt = 24; spec(1).model = 1; spec(1).meteoData = 3;
spec(1).trainStart = [1 10 2008]; spec(1).trainEnd = [30 9 2015];
spec(1).evalStart = [1 10 2000]; spec(1).evalEnd = [30 9 2008];
spec(1).output = fullfile(repo,'projects','P03_CAMELS_US_hourly', ...
    'run_SAGE_export_project_03.m');

spec(2) = common;
spec(2).project = 'Project 4';
spec(2).name = 'SAGE GUI, Germany hourly';
spec(2).modelName = 'hbv';
spec(2).resolution = 'Hourly';
spec(2).title = ['SAGE GUI: Fast and Flexible Differentiable Hydrologic ' ...
    'Modeling with Analytic Gradients'];
spec(2).summary = ['GUI publication experiment using Germany hourly data ' ...
    'and the prescribed 1000/259 basin split.'];
spec(2).region = 'CAMELS_DEH';
spec(2).regionName = 'Germany (CAMELS-DE-1h)';
spec(2).dataRoot = 'CAMELS_DE';
spec(2).meteoPath = fullfile('hourly','timeseries');
spec(2).qPath = fullfile('hourly','timeseries');
spec(2).fileUniverse = 'DEH_1259_basins.txt';
spec(2).fileSplit = 'split_DEH_1259_1000_259_1.txt';
spec(2).K = 1259; spec(2).Kt = 1000; spec(2).Ke = 259;
spec(2).dt = 24; spec(2).model = 6;
spec(2).trainStart = [1 10 2013]; spec(2).trainEnd = [30 9 2021];
spec(2).evalStart = [1 10 2005]; spec(2).evalEnd = [30 9 2013];
spec(2).output = fullfile(repo,'projects','P04_GUI_Germany_hourly', ...
    'run_SAGE_export_project_04.m');

spec(3) = common;
spec(3).project = 'Project 5';
spec(3).name = 'Switzerland multivariable';
spec(3).modelName = 'hbv';
spec(3).resolution = 'Daily';
spec(3).dataType = ['Discharge, snow water equivalent and soil ' ...
    'moisture content'];
spec(3).title = ['Beyond Streamflow: Dual- and Triple-Response Hydrologic ' ...
    'Learning across Switzerland with SAGE'];
spec(3).summary = ['Daily HYD-RESPONSES experiment fitting discharge, ' ...
    'snow-water equivalent, and soil moisture jointly with HBV.'];
spec(3).region = 'HYD_RESPONSES';
spec(3).regionName = 'Switzerland';
spec(3).dataRoot = 'HYD_RESPONSES';
spec(3).meteoPath = fullfile('daily','timeseries');
spec(3).qPath = fullfile('daily','timeseries');
spec(3).fileUniverse = 'HYD_184_basins.txt';
spec(3).fileSplit = 'split_HYD_184_150_34_1.txt';
spec(3).K = 184; spec(3).Kt = 150; spec(3).Ke = 34;
spec(3).dt = 1; spec(3).model = 6;
spec(3).trainStart = [1 1 2007]; spec(3).trainEnd = [31 12 2014];
spec(3).evalStart = [1 1 2015]; spec(3).evalEnd = [31 12 2022];
spec(3).observed = '{''Q'', ''SWE'', ''SM''}';
spec(3).weights = ['loss.weight.Q = 1/3;' newline ...
    'loss.weight.SWE = 1/3;' newline 'loss.weight.SM = 1/3;' newline];
spec(3).output = fullfile(repo,'projects','P05_multivariable_MACH', ...
    'run_SAGE_export_project_05.m');

for k = 1:numel(spec)
    spec(k).headerLiteral = sprintf( ...
        '{''%s'',''%s'';''Title'',''%s'';''Summary'',''%s''}', ...
        spec(k).project,escape(spec(k).name),escape(spec(k).title), ...
        escape(spec(k).summary));
end
end

function text = header_text(s)
periodStart = min(local_date(s.trainStart),local_date(s.evalStart));
periodEnd = max(local_date(s.trainEnd),local_date(s.evalEnd));
exported = char(datetime('now','Format','dd-MMM-yyyy HH:mm:ss'));
detailRows = { ...
    'Model',s.modelName; ...
    'Region',s.regionName; ...
    'Resolution',s.resolution; ...
    'Basins',sprintf('%d (training: %d; evaluation: %d)', ...
        s.K,s.Kt,s.Ke); ...
    'Period',sprintf('%s - %s',local_date_text(periodStart), ...
        local_date_text(periodEnd)); ...
    'Temporal split','Manual dates'; ...
    'Training',sprintf('%s - %s',local_date_text(local_date(s.trainStart)), ...
        local_date_text(local_date(s.trainEnd))); ...
    'Evaluation',sprintf('%s - %s',local_date_text(local_date(s.evalStart)), ...
        local_date_text(local_date(s.evalEnd))); ...
    'Loss function',s.lossName; ...
    'Data type',s.dataType; ...
    'Optimizer',s.optimizerName; ...
    'Exported',exported};
text = sprintf([ ...
    '%% ========================================================================\n' ...
    '%%   S A G E\n' ...
    '%%   Sensitivity-Aware Learning for Rapid Training of Process-Based\n' ...
    '%%   Hydrologic Models across Large Basin Samples\n' ...
    '%% ========================================================================\n' ...
    '%%\n%s%%\n%s%%\n' ...
    '%% Generated from the canonical SAGE GUI run-export pipeline.\n\n' ...
    'clear\nclc\n\nwallTimerTotal = tic; wallTData = 0;\n'], ...
    comment_rows({s.project,s.name;'Title',s.title;'Summary',s.summary}), ...
    comment_rows(detailRows));
end

function value = local_date(v)
value = datetime(v(3),v(2),v(1));
end

function value = local_date_text(v)
value = char(string(v,'dd MMM yyyy'));
end

function text = configuration_text(s)
idAttr = ['[1 2 4 5 6 7 9 10 16 18 32 33 34 35 36 37 38 39 ...' ...
    newline '    45 46 47 49 50 51 52 53]'];
text = sprintf([ ...
    '%%%% Installation and data paths\n' ...
    'projectFolder = fileparts(mfilename(''fullpath''));\n' ...
    'SAGEhydro = fileparts(fileparts(projectFolder));\n' ...
    'root = fileparts(SAGEhydro);\n' ...
    'SAGEdir = SAGEhydro;\n' ...
    'region = ''%s'';\nregionName = ''%s'';\n' ...
    'file_univ = ''%s'';\nfile_split = ''%s'';\n' ...
    'dirDroot = fullfile(root,''Data'');\n' ...
    'dirD = fullfile(dirDroot,''%s'');\n' ...
    'dirM = fullfile(dirD,%s);\ndirQ = fullfile(dirD,%s);\n' ...
    'dirres = fullfile(SAGEhydro,''results'');\n\n' ...
    '%%%% Model configuration\nmdl.model = %d;\nmdl.mcode = 4;\n' ...
    'mdl.calc = ''parfeval'';\nmdl.mode = 4;\n\n' ...
    '%%%% Basin selection and attributes\nbas.K = %d;\nbas.K_t = %d;\n' ...
    'bas.K_e = %d;\nbas.sample = ''file'';\nbas.id_attr = %s;\n' ...
    'bas.pr_attr = 0;\nbas.dt = %d;\nbas.mode = 4;\n\n' ...
    '%%%% Training and evaluation periods\nprd.dt = %d;\n' ...
    'prd.method = ''manual'';\nprd.dts = %s;\nprd.dte = %s;\n' ...
    'prd.des = %s;\nprd.dee = %s;\nprd.spinup = 365;\n' ...
    'prd.eval_was_empty = false;\nprd.eval_partial = false;\n\n' ...
    '%%%% Feedforward neural-network settings\nnet.h = 32;\n' ...
    'net.tf = {''tanh''};\nnet.seed = 0;\n\n' ...
    '%%%% Loss-function settings\nloss.fnc = 2;\nloss.method = 1;\n' ...
    'loss.n_win = 7;\nloss.M = 2;\nloss.observed = %s;\n%s' ...
    'loss.normalization.method = ''auto'';\n\n' ...
    '%%%% Optimization settings\nalg.method = 2;\nalg.i_max = 250;\n' ...
    'alg.lr = 0.01;\nalg.beta_1 = 0.9;\nalg.beta_2 = 0.999;\n' ...
    'alg.vareps = 1e-8;\nalg.wdecay = 1e-4;\nalg.clipn = 1;\n' ...
    'alg.lr_min = 1e-4;\nalg.lr_scheme = ''constant'';\n' ...
    'alg.lr_hold = 0.2;\n\n' ...
    '%%%% Numerical solver settings\node.InitStep = 0.01;\n' ...
    'ode.MaxStep = 1;\node.MinStep = 1e-4;\node.RelTol = 1e-3;\n' ...
    'ode.AbsTol = 1e-3;\node.Order = 2;\node.maxiter = 10000;\n' ...
    'ode.mem = 0;\n\n' ...
    '%%%% Miscellaneous forcing, output, and plotting settings\n' ...
    'misc.meteo.data = %d;\nmisc.meteo.precip = %d;\n' ...
    'misc.meteo.temp = %d;\nmisc.meteo.pet = 1;\n' ...
    'misc.io.prt = 1;\nmisc.io.file = 1;\nmisc.attr = 0;\n' ...
    'misc.attr_view = ''abs'';\nmisc.plot.Btr = 5;\nmisc.plot.Bev = 5;\n' ...
    'misc.plot.gaugescen.tt = {};\nmisc.plot.gaugescen.te = {};\n' ...
    'misc.plot.gaugescen.et = {};\nmisc.plot.gaugescen.ee = {};\n' ...
    'misc.crr_backend = ''cpp'';\n\nparOverride = struct();\n\n'], ...
    s.region,s.regionName,s.fileUniverse,s.fileSplit,s.dataRoot, ...
    path_literal(s.meteoPath),path_literal(s.qPath),s.model,s.K,s.Kt,s.Ke, ...
    idAttr,s.dt,s.dt,mat2str(s.trainStart),mat2str(s.trainEnd), ...
    mat2str(s.evalStart),mat2str(s.evalEnd),s.observed,s.weights, ...
    s.meteoData,s.meteoData,s.meteoData);
end

function text = header_call(s)
text = sprintf([ ...
    'projectInfo = jsondecode(fileread( ...\n' ...
    '    fullfile(projectFolder,''project.json'')));\n' ...
    'projectHeader = {''%s'',projectInfo.name; ...\n' ...
    '    ''Title'',projectInfo.paper_title; ...\n' ...
    '    ''Summary'',projectInfo.summary};\n' ...
    'write_header(mdl,''sage'',projectHeader) '],s.project);
end

function value = path_literal(path)
parts = split(string(path),filesep);
value = strjoin("'" + parts + "'",',');
value = char(value);
end

function text = comment_rows(rows)
labelWidth = 15;
valueWidth = 76-(2+labelWidth+2);
text = '';
for k = 1:size(rows,1)
    lines = wrap_text(rows{k,2},valueWidth);
    for j = 1:numel(lines)
        label = '';
        separator = '  ';
        if j == 1
            label = rows{k,1};
            separator = ': ';
        end
        text = [text sprintf('%% %-*s%s%s\n',labelWidth,label, ...
            separator,lines{j})]; %#ok<AGROW>
    end
end
end

function lines = wrap_text(value,width)
words = regexp(strtrim(char(string(value))),'\s+','split');
lines = {};
current = '';
for k = 1:numel(words)
    candidate = strtrim([current ' ' words{k}]);
    if isempty(current) || numel(candidate) <= width
        current = candidate;
    else
        lines{end+1} = current; %#ok<AGROW>
        current = words{k};
    end
end
lines{end+1} = current;
end

function value = escape(value)
value = strrep(char(string(value)),'''','''''');
end
