function varargout = region_helpers(action,varargin)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%REGION_HELPERS Centralized region metadata and lookup utility for SAGE.
%
% SYNOPSIS:
%   out = region_helpers(action,...)
%   [latLim,lonLim,mapName] = region_helpers('maplimits',region,lat,lon)
%
% INPUT:
%   action   Character/string specifying the requested region operation:
%              'code'            canonical CAMELS region code
%              'short'           short region tag
%              'name'            display name
%              'regiondir'       region-module directory path
%              'basindir'        compatibility alias for regiondir
%              'basinfile'       region-prefixed basin/split filename
%              'maplimits'       registered map limits; optional basin
%                                coordinates are used as a generic fallback
%              'capital'         capital city latitude, longitude, and name
%              'variogramrange'  default variogram fitting range
%              'variogramtick'   default variogram tick spacing
%              'naturalearth'    Natural Earth country name
%              'config'          load regions/XX/region_config_XX.m
%              'resolutions'     supported resolutions from the config
%              'resolution'      selected resolution-specific config
%              'resolvepaths'    resolve dirD/dirM/dirQ from a config
%              'list'            display names and canonical codes
%
%   varargin Additional inputs required by the selected action
%
% OUTPUT:
%   varargout Output requested by action
%
% DESCRIPTION:
%   This helper provides a single registry-based interface for region
%   metadata used throughout SAGE-GUI. It maps aliases, folder names,
%   structures with region or dirD fields, and canonical CAMELS identifiers
%   to a consistent regional definition. The registry controls short tags,
%   display names, map limits, Natural Earth names, basin filename prefixes
%   and variogram plotting defaults.
%
% NOTES:
%   New regions should be added only in region_registry using 1 additional
%   reg(...) entry. The remaining helper functions use the registry and do
%   not require region-specific edits.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% © Written by Jasper A. Vrugt, June 2026                                 %
% University of California, Irvine                                        %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    switch lower(action)
    
        case 'code'
            varargout{1} = ...
                region_code(varargin{:});
    
        case 'short'
            varargout{1} = ...
                region_short(varargin{:});
    
        case 'name'
            varargout{1} = ...
                region_name(varargin{:});
    
        case {'regiondir','basindir'}
            varargout{1} = ...
                fullfile(varargin{1}, ...
                'regions',region_short(varargin{2}));
    
        case 'basinfile'
            varargout{1} = ...
                region_basin_file(varargin{:});
    
        case 'maplimits'
            [varargout{1:nargout}] = ...
                region_map_limits(varargin{:});
    
        case 'capital'
            [varargout{1:nargout}] = ...
                region_capital(varargin{:});
            
        case 'variogramrange'
            varargout{1} = ...
                region_variogram_range(varargin{:});
    
        case 'variogramtick'
            varargout{1} = ...
                region_variogram_tick_step(varargin{:});
    
        case {'naturalearth','country','country_name'}
            varargout{1} = region_naturalearth_name(varargin{:});

        case 'config'
            varargout{1} = region_config_load(varargin{:});

        case 'resolutions'
            C = region_config_load(varargin{:});
            varargout{1} = C.resolutions;

        case {'resolution','resolutionconfig'}
            C = region_config_load(varargin{1},varargin{2});
            varargout{1} = region_resolution_config(C,varargin{3});

        case {'resolvepaths','paths'}
            varargout{1} = region_resolve_paths(varargin{:});

        case {'list','regions'}
            R = region_registry();
            varargout{1} = {R.name};
            if nargout > 1
                varargout{2} = {R.code};
            end

        otherwise
            varargout{1} = 'CAMELS_US';
    end
end

function R = region_registry()

    R = reg('CAMELS_AR','AR','Argentina', ...
        'Argentina',[-56 -21],[-74 -53],'Argentina', ...
        "Buenos Aires",-34.6037,-58.3816,1800,300, ...
        {'AR','ARG','ARGENTINA','CAMELS_AR'});

    R(end+1) = reg('CAMELS_AU','AU','Australia', ...
        'Australia',[-44 -10],[112 154],'Australia', ...
        "Canberra",-35.2809,149.1300, ...
        2500,500, ...
        {'AU','AUS','AUSTRALIA','CAMELS_AU','CAMELS_AUS'});

    R(end+1) = reg('CAMELS_AT','AT','Austria', ...
        'Austria',[46.2 50.2],[8 19],'Austria', ...
        "Vienna",48.2082,16.3738, ...
        500,100, ...
        {'AT','AUT','AUSTRIA','CAMELS_AT','CAMELS_AUSTRIA'});

    R(end+1) = reg('CAMELS_BE','BE','Belgium', ...
        'Belgium',[49.4 51.6],[2.5 6.5],'Belgium', ...
        "Brussels",50.8503,4.3517,150,30, ...
        {'BE','BEL','BELGIUM','CAMELS_BE'});

    R(end+1) = reg('CAMELS_BR','BR','Brazil', ...
        'Brazil',[-34 6],[-75 -34],'Brazil', ...
        "Brasilia",-15.7939,-47.8828, ...
        3500,1000, ...
        {'BR','BRA','BRAZIL','CAMELS_BR'});

    R(end+1) = reg('CAMELS_CA','CA','Canada', ...
        'Canada',[42 72],[-145 -45],'Canada', ...
        "Ottawa",45.4215,-75.6972, ...
        4500,1000, ...
        {'CA','CAN','CANADA','CAMELS_CA','CAMELS_CANADA', ...
        'CAMELS_SPAT','CAMELS-SPAT'});

    R(end+1) = reg('CAMELS_CL','CL','Chile', ...
        'Chile',[-56 -17],[-76 -66],'Chile', ...
        "Santiago",-33.4489,-70.6693, ...
        2500,500, ...
        {'CL','CHILE','CAMELS_CL','CAMELS_CHILE'});

    R(end+1) = reg('CAMELS_COL','COL','Colombia', ...
        'Colombia',[-2 10],[-80 -65],'Colombia', ...
        "Bogota",4.7110,-74.0721, ...
        800,200, ...
        {'COL','COLOMBIA','COLUMBIA','CAMELS_COL', ...
        'CAMELS_COLOMBIA','CAMELS_COLUMBIA'});

    R(end+1) = reg('CAMELS_CZ','CZ','Czechia', ...
        'Czechia',[48.4 51.2],[11.8 19.1],'Czechia', ...
        "Prague",50.0755,14.4378, ...
        300,50, ...
        {'CZ','CZE','CZECHIA','CZECH REPUBLIC', ...
        'CESKO','CAMELS_CZ','CAMELS_CZECHIA', ...
        'CAMELS_CZECH_REPUBLIC'});

    R(end+1) = reg('CAMELS_DK','DK','Denmark', ...
        'Denmark',[54.4 57.9],[7.5 15.3],'Denmark', ...
        "Copenhagen",55.6761,12.5683, ...
        250,50, ...
        {'DK','DNK','DENMARK','DANMARK', ...
        'CAMELS_DK','CAMELS_DENMARK'});

    R(end+1) = reg('CAMELS_EE','EE','Estonia', ...
        'Estonia',[57.4 59.8],[21.5 28.3],'Estonia', ...
        "Tallinn",59.4370,24.7536,200,50, ...
        {'EE','EST','ESTONIA','CAMELS_EE'});

    R(end+1) = reg('CAMELS_FI','FI','Finland', ...
        'Finland',[59.5 70.5],[15 38],'Finland', ...
        "Helsinki",60.1699,24.9384, ...
        800,200, ...
        {'FI','FIN','FINLAND','CAMELS_FI','CAMELS_FINLAND'});

    R(end+1) = reg('CAMELS_FR','FR','France', ...
        'France',[41.5 51.2],[-7.5 10],'France', ...
        "Paris",48.8566,2.3522, ...
        800,200, ...
        {'FR','FRA','FRANCE','CAMELS_FR','CAMELS_FRANCE'});

    R(end+1) = reg('CAMELS_DE','DE','Germany', ...
        'Germany',[47.2 55.1],[5.5 15.5],'Germany', ...
        "Berlin",52.5200,13.4050, ...
        600,100, ...
        {'DE','GERMANY','CAMELS_DE','CAMELS_GERMANY'});

    R(end+1) = reg('CAMELS_GB','GB','Great Britain', ...
        'United Kingdom',[49.5 59.5],[-8.5 2.5], ...
        'Great Britain', ...
        "London",51.5072,-0.1276, ...
        800,200, ...
        {'GB','UK','GREAT BRITAIN','UNITED KINGDOM','CAMELS_GB'});

    R(end+1) = reg('CAMELS_IS','IS','Iceland', ...
        'Iceland',[63.2 66.8],[-24.8 -13.2],'Iceland', ...
        "Reykjavik",64.1466,-21.9426, ...
        300,50, ...
        {'IS','ISL','ICELAND','CAMELS_IS','CAMELS_ICELAND'});

    R(end+1) = reg('CAMELS_IND','IND','India', ...
        'India',[6 32],[70 90],'India', ...
        "New Delhi",28.6139,77.2090, ...
        1000,200, ...
        {'IND','INDIA','CAMELS_IND'});

    R(end+1) = reg('CAMELS_IE','IE','Ireland', ...
        'Ireland',[51.3 55.5],[-11 -5.2],'Ireland', ...
        "Dublin",53.3498,-6.2603,200,40, ...
        {'IE','IRL','IRELAND','CAMELS_IE'});

    R(end+1) = reg('CAMELS_IL','IL','Israel', ...
        'Israel',[29.3 33.5],[34.1 35.9],'Israel', ...
        "Jerusalem",31.7683,35.2137, ...
        300,50, ...
        {'IL','ISR','ISRAEL','CAMELS_IL','CAMELS_ISRAEL'});

    R(end+1) = reg('CAMELS_JM','JM','Jamaica', ...
        'Jamaica',[17.6 18.6],[-78.5 -76],'Jamaica', ...
        "Kingston",17.9712,-76.7936,100,20, ...
        {'JM','JAM','JAMAICA','CAMELS_JM'});

    R(end+1) = reg('CAMELS_JP','JP','Japan', ...
        'Japan',[30 46],[127 146],'Japan', ...
        "Tokyo",35.6762,139.6503,800,200, ...
        {'JP','JPN','JAPAN','CAMELS_JP','MERV_JP','MERV-JP'});

    R(end+1) = reg('CAMELS_LUX','LUX','Luxembourg', ...
        'Luxembourg',[49.4 50.2],[5.5 6.5],'Luxembourg', ...
        "Luxembourg",49.6116,6.1319, ...
        60,10, ...
        {'LUX','LUXEMBOURG','CAMELS_LUX'});

    R(end+1) = reg('CAMELS_MX','MX','Mexico', ...
        'Mexico',[14 33],[-119 -86],'Mexico', ...
        "Mexico City",19.4326,-99.1332, ...
        1200,300, ...
        {'MX','MEX','MEXICO','CAMELS_MX', ...
        'HYSETS_MX','CARAVAN_HYSETS_MX'});

    R(end+1) = reg('CAMELS_NA','NA','Namibia', ...
        'Namibia',[-29 -16.5],[11 26],'Namibia', ...
        "Windhoek",-22.5609,17.0658,1000,200, ...
        {'NA','NAM','NAMIBIA','GRDC_NAMIBIA','CAMELS_NA'});

    R(end+1) = reg('CAMELS_NZ','NZ','New Zealand', ...
        'New Zealand',[-47.5 -34.0],[166.0 179.5], ...
        'New Zealand', ...
        "Wellington",-41.2865,174.7762, ...
        1200,300, ...
        {'NZ','NZL','NEW_ZEALAND','NEW ZEALAND','AOTEAROA', ...
        'CAMELS_NZ','CAMELS_NEW_ZEALAND'});

    R(end+1) = reg('CAMELS_NO','NO','Norway', ...
        'Norway',[57 72],[4 32],'Norway', ...
        "Oslo",59.9139,10.7522,1200,300, ...
        {'NO','NOR','NORWAY','CAMELS_NO'});

    R(end+1) = reg('CAMELS_PE','PE','Peru', ...
        'Peru',[-19 1],[-82 -68],'Peru', ...
        "Lima",-12.0464,-77.0428, ...
        1800,300, ...
        {'PE','PER','PERU','PERÚ','CAMELS_PE','CAMELS_PERU'});

    R(end+1) = reg('CAMELS_PL','PL','Poland', ...
        'Poland',[48.5 55.2],[13.5 24.5],'Poland', ...
        "Warsaw",52.2297,21.0122, ...
        600,100, ...
        {'PL','POLAND','CAMELS_PL','CAMELS_POLAND'});

    R(end+1) = reg('CAMELS_PR','PR','Puerto Rico', ...
        'Puerto Rico',[17.7 18.6],[-67.4 -65.1],'Puerto Rico', ...
        "San Juan",18.4655,-66.1057,100,20, ...
        {'PR','PRI','PUERTO RICO','PUERTO_RICO','CAMELS_PR'});

    R(end+1) = reg('CAMELS_ZA','ZA','South Africa', ...
        'South Africa',[-35 -22],[16 33],'South Africa', ...
        "Pretoria",-25.7479,28.2293, ...
        1200,300, ...
        {'ZA','ZAF','SOUTH AFRICA','GRDC-CARAVAN', ...
        'GRDC_CARAVAN','CAMELS_ZA'});

    R(end+1) = reg('CAMELSH_KR','KR','South Korea', ...
        'South Korea',[34.5 39],[125.5 130],'South Korea', ...
        "Seoul",37.5665,126.9780, ...
        300,50, ...
        {'KR','KOR','KOREA','SOUTH KOREA','REPUBLIC OF KOREA', ...
        'CAMELSH_KR','CAMELSH-KR'});

    R(end+1) = reg('CAMELS_ES','ES','Spain (CAMELS)', ...
        'Spain',[35 44.5],[-10 4.5],'Spain', ...
        "Madrid",40.4168,-3.7038, ...
        800,200, ...
        {'ES','ESP','SPAIN','CAMELS_ES','CAMELS_ESP', ...
        'SPAIN (CAMELS)'});

    R(end+1) = reg('BULL_ES','BULL','Spain (BULL)', ...
        'Spain',[35 44.5],[-10 4.5],'Spain', ...
        "Madrid",40.4168,-3.7038, ...
        1000,200, ...
        {'BULL','BULL_ES','BULL-ES','SPAIN BULL', ...
        'SPAIN (BULL)'});

    R(end+1) = reg('CAMELS_SE','SE','Sweden', ...
        'Sweden',[55.5 69.5],[11 24.5],'Sweden', ...
        "Stockholm",59.3293,18.0686, ...
        1200,300, ...
        {'SE','SWE','CAMELS_SE','CAMELS_SWEDEN'});

    R(end+1) = reg('CAMELS_CH','CH','Switzerland', ...
        'Switzerland',[45.7 47.9],[5.8 10.6],'Switzerland', ...
        "Bern",46.9480,7.4474, ...
        300,50, ...
        {'CH','CHE','SWISS','SWITZERLAND', ...
        'CAMELS_CH','CAMELS_SWITZERLAND'});

    R(end+1) = reg('CAMELS_US','US','United States (CAMELS)', ...
        'United States of America',[26 49],[-124 -67], ...
        'CONUS', ...
        "Washington, DC",38.9072,-77.0369, ...
        3750,1000, ...
        {'US','USA','U.S.','U.S.A.','CONUS', ...
        'UNITED STATES','UNITED STATES OF AMERICA','CAMELS_US', ...
        'UNITED STATES (CAMELS)','UNITED STATES (CAMELS-US)'});

    R(end+1) = reg('CAMELSH_US','USH','United States (CAMELSH)', ...
        'United States of America',[26 49],[-124 -67], ...
        'CONUS', ...
        "Washington, DC",38.9072,-77.0369, ...
        3750,1000, ...
        {'USH','CAMELSH','CAMELSH_US','CAMELSH-US', ...
        'UNITED STATES CAMELSH','US CAMELSH', ...
        'UNITED STATES (CAMELSH)'});

    R(end+1) = reg('MACH_US','MACH','United States (MACH)', ...
        'United States of America',[26 49],[-124 -67], ...
        'CONUS', ...
        "Washington, DC",38.9072,-77.0369, ...
        3750,1000, ...
        {'MACH','MACH_US','MACH-US','UNITED STATES MACH','US MACH', ...
        'UNITED STATES (MACH)'});

end

function r = reg(code,short,name,country, ...
    latLim,lonLim,mapName, ...
    capitalName,capitalLat,capitalLon, ...
    hmax,tick,aliases)

    r = struct('code',code, ...
        'short',short, ...
        'name',name, ...
        'country',country, ...
        'latLim',latLim, ...
        'lonLim',lonLim, ...
        'mapName',mapName, ...
        'capitalName',string(capitalName), ...
        'capitalLat',capitalLat, ...
        'capitalLon',capitalLon, ...
        'hmax',hmax, ...
        'tick',tick, ...
        'aliases',{upper(string(aliases))});
end

function R = region_lookup(v)

    if nargin == 0 ...
            || isempty(v)
        v = 'CAMELS_FR';
    end
    
    if isstruct(v)
        if isfield(v,'region') ...
                && ~isempty(v.region)
            v = v.region;
        elseif isfield(v,'dirD') ...
                && ~isempty(v.dirD)
            v = v.dirD;
        else
            v = 'CAMELS_FR';
        end
    end

    Rall = region_registry();
    s = upper(strtrim(string(v)));
    s = replace(s,'-','_');
    sChar = char(s);
    for k = 1:numel(Rall)
        if contains(sChar,Rall(k).code)
            R = Rall(k);
            return
        end
    end
    for k = 1:numel(Rall)
        if any(s == Rall(k).aliases) ...
                || s == Rall(k).code
            R = Rall(k);
            return
        end
    end
    idx = strcmp({Rall.code},'CAMELS_US');
    R = Rall(idx);

end

function region = region_code(v)
    R = region_lookup(v);
    region = R.code;
end

function short = region_short(region)
    R = region_lookup(region);
    short = R.short;
end

function name = region_name(region)
    R = region_lookup(region);
    name = R.name;
end

function [lat,lon,name] = region_capital(region)
    R = region_lookup(region);
    lat = R.capitalLat;
    lon = R.capitalLon;
    name = R.capitalName;
end

function country = region_naturalearth_name(region)
    R = region_lookup(region);
    country = R.country;
end

function hmax_fit = region_variogram_range(region)
    R = region_lookup(region);
    hmax_fit = R.hmax;
end

function tickStep = region_variogram_tick_step(region)
    R = region_lookup(region);
    tickStep = R.tick;
end

function [latLim,lonLim,mapName] = region_map_limits(region,lat,lon)

    R = region_lookup(region);
    latLim = double(R.latLim);
    lonLim = double(R.lonLim);
    mapName = char(R.mapName);

    % The registry is the single source of region-specific map limits.
    % Coordinates are only a generic fallback when a newly added registry
    % entry accidentally contains missing or invalid limits.
    if local_valid_limits(latLim,lonLim)
        return
    end

    latLim = [];
    lonLim = [];
    if nargin >= 3 ...
            && ~isempty(lat) ...
            && ~isempty(lon)
        coords = [lat(:),lon(:)];
        [latLim,lonLim] = localCoordinateMapLimits(coords);
    end

    if ~local_valid_limits(latLim,lonLim)
        error('region_helpers:InvalidMapLimits', ...
            ['Region %s has invalid map limits. ' ...
            'Update its single reg(...) ' ...
             'entry in region_registry.'],R.code);
    end
end

function [latLim,lonLim] = localCoordinateMapLimits(coords)
    latLim = [];
    lonLim = [];
    if isempty(coords) ...
            || ~isnumeric(coords) ...
            || size(coords,2) < 2
        return
    end
    lat = double(coords(:,1));
    lon = double(coords(:,2));
    good = isfinite(lat) ...
        & isfinite(lon) ...
        & lat >= -90 ...
        & lat <= 90 ...
        & lon >= -180 ...
        & lon <= 180;
    lat = lat(good);
    lon = lon(good);
    if isempty(lat)
        return
    end
    dlat = max(0.5,0.10*max(max(lat)-min(lat),1));
    dlon = max(0.5,0.10*max(max(lon)-min(lon),1));
    latLim = [max(-90,min(lat)-dlat), min(90,max(lat)+dlat)];
    lonLim = [max(-180,min(lon)-dlon), min(180,max(lon)+dlon)];
end

function tf = local_valid_limits(latLim,lonLim)
    tf = isnumeric(latLim) ...
        && isnumeric(lonLim) ...
        && numel(latLim) == 2 ...
        && numel(lonLim) == 2 ...
        && all(isfinite(latLim)) ...
        && all(isfinite(lonLim)) ...
        && latLim(1) < latLim(2) ...
        && lonLim(1) < lonLim(2);
end


function C = region_config_load(SAGEhydro,region)
%REGION_CONFIG_LOAD Load regions/XX/region_config_XX.m.

    if nargin < 2
        error('region_helpers:ConfigInputs', ...
            'Provide the SAGEhydrology directory and region.');
    end

    sageDir = char(string(SAGEhydro));
    short = region_short(region);
    cfgDir = fullfile(sageDir,'regions',short);
    cfgFile = fullfile(cfgDir,['region_config_' short '.m']);

    % In normal MATLAB, verify the source file and temporarily add its
    % region folder to the path. In a deployed application, the config
    % functions are compiled into the CTF and do not need to exist as
    % loose .m files beside the executable.
    if ~isdeployed
        if ~isfile(cfgFile)
            error('region_helpers:MissingRegionConfig', ...
                'Regional configuration file not found: %s',cfgFile);
        end

        wasOnPath = local_path_contains(cfgDir);
        if ~wasOnPath
            addpath(cfgDir);
            cleanupPath = onCleanup(@()local_remove_path(cfgDir));
        end
    end

    % Explicit dispatch keeps MATLAB Compiler dependencies visible.
    switch short
        case 'AT'
            C = region_config_AT();
        case 'AR'
            C = region_config_AR();
        case 'BE'
            C = region_config_BE();
        case 'AU'
            C = region_config_AU();
        case 'BR'
            C = region_config_BR();
        case 'BULL'
            C = region_config_BULL();
        case 'CA'
            C = region_config_CA();
        case 'CH'
            C = region_config_CH();
        case 'CL'
            C = region_config_CL();
        case 'COL'
            C = region_config_COL();
        case 'CZ'
            C = region_config_CZ();
        case 'DE'
            C = region_config_DE();
        case 'DK'
            C = region_config_DK();
        case 'ES'
            C = region_config_ES();
        case 'EE'
            C = region_config_EE();
        case 'FI'
            C = region_config_FI();
        case 'FR'
            C = region_config_FR();
        case 'GB'
            C = region_config_GB();
        case 'IL'
            C = region_config_IL();
        case 'IND'
            C = region_config_IND();
        case 'IS'
            C = region_config_IS();
        case 'IE'
            C = region_config_IE();
        case 'JM'
            C = region_config_JM();
        case 'JP'
            C = region_config_JP();
        case 'KR'
            C = region_config_KR();
        case 'LUX'
            C = region_config_LUX();
        case 'MACH'
            C = region_config_MACH();
        case 'MX'
            C = region_config_MX();
        case 'NA'
            C = region_config_NA();
        case 'NZ'
            C = region_config_NZ();
        case 'NO'
            C = region_config_NO();
        case 'PE'
            C = region_config_PE();
        case 'PL'
            C = region_config_PL();
        case 'PR'
            C = region_config_PR();
        case 'SE'
            C = region_config_SE();
        case 'US'
            C = region_config_US();
        case 'USH'
            C = region_config_USH();
        case 'ZA'
            C = region_config_ZA();
        otherwise
            error('region_helpers:UnknownRegionConfig', ...
                ['No regional configuration ' ...
                'is registered for %s.'],short);
    end

    if ~isstruct(C) || ~isfield(C,'code') ...
            || ~isfield(C,'resolutions') ...
            || ~isfield(C,'by_resolution')
        error('region_helpers:InvalidRegionConfig', ...
            ['%s did not return the expected ' ...
            'configuration structure.'], ...
            cfgFile);
    end

    expected = region_code(region);
    if ~strcmpi(char(string(C.code)),expected)
        error('region_helpers:RegionConfigMismatch', ...
            ['Configuration %s declares ' ...
            '%s, but %s was requested.'], ...
            cfgFile,char(string(C.code)),expected);
    end
end

function X = region_resolution_config(C,resolution)
%REGION_RESOLUTION_CONFIG Return one resolution-specific block.

    requested = char(string(resolution));
    key = strrep(requested,' ','_');
    if strcmpi(key,'15_minutes')
        key = 'min15';
    end

    fields = fieldnames(C.by_resolution);
    idx = find(strcmpi(fields,key),1);

    if isempty(idx)
        error('region_helpers:UnsupportedResolution', ...
            '%s does not support resolution "%s".', ...
            C.code,requested);
    end

    X = C.by_resolution.(fields{idx});
end


function P = region_resolve_paths(C,X,dataRoot)
%REGION_RESOLVE_PATHS Resolve generic regional runtime directories.
%
% All X.paths entries are relative to Data/<C.data_root>.

    if nargin < 3
        error('region_helpers:PathInputs', ...
            ['Provide region config, ' ...
            'resolution config, and data root.']);
    end
    if ~isstruct(C) ...
            || ~isfield(C,'data_root')
        error('region_helpers:InvalidPathConfig', ...
            'The region configuration lacks data_root.');
    end
    if ~isstruct(X) ...
            || ~isfield(X,'paths')
        error('region_helpers:InvalidResolutionPaths', ...
            'The resolution configuration lacks paths.');
    end

    regionRoot = fullfile(char(string(dataRoot)), ...
        char(string(C.data_root)));

    runRoot = '';
    if isfield(X.paths,'run_root')
        runRoot = char(string(X.paths.run_root));
    elseif isfield(X.paths,'region_subdir')
        % Transitional compatibility with older configuration files.
        runRoot = char(string(X.paths.region_subdir));
    end

    P = struct();
    P.data_root = char(string(dataRoot));
    P.region_root = regionRoot;
    P.dirD = local_join_relative(regionRoot, ...
        runRoot);
    P.dirM = local_join_relative(regionRoot, ...
        X.paths.meteo);
    P.dirQ = local_join_relative(regionRoot, ...
        X.paths.discharge);
    P.dt = double(X.dt);
end

function out = local_join_relative(base,relativePath)
    rel = char(string(relativePath));
    if isempty(strtrim(rel))
        out = base;
    else
        out = fullfile(base,rel);
    end
end

function tf = local_path_contains(folder)
    entries = strsplit(path,pathsep);
    tf = any(strcmpi(string(entries),string(folder)));
end

function local_remove_path(folder)
    try
        if local_path_contains(folder)
            rmpath(folder);
        end
    catch
    end
end

function fname = region_basin_file(region,fname)

    fname = char(strtrim(string(fname)));
    
    if isempty(fname) ...
            || isfile(fname) ...
            || contains(fname,filesep)
        return
    end
    
    [pth,nam,ext] = fileparts(fname);
    if ~isempty(pth)
        return
    end
    
    r = region_short(region);
    
    R = region_registry();
    shorts = string({R.short});
    [~,ix] = sort(strlength(shorts),'descend');
    shorts = shorts(ix);
    pat = ['(' char(strjoin(shorts + "_","|")) ')'];
    
    if startsWith(nam,'split_')
        nam = regexprep(nam, ...
            ['^split_' pat '?'], '');
        fname = ['split_' r '_' nam ext];
    else
        nam = regexprep(nam, ...
            ['^' pat], '');
        fname = [r '_' nam ext];
    end

end
