function theme = sage_visual_theme(uiScale,screenWidth)
%SAGE_VISUAL_THEME Canonical visual design tokens for SAGE and SITE.
%
%   THEME = SAGE_VISUAL_THEME() returns the authoritative colors, font
%   sizes, line widths, marker sizes, axis settings, and spacing tokens
%   used by the graphical interfaces and exported figures. Consumers
%   should read these values instead of embedding new numeric styles.
%
%   THEME = SAGE_VISUAL_THEME(UISCALE,SCREENWIDTH) also returns scaled GUI
%   fonts. Initial values reproduce the current appearance; introducing
%   the theme must not by itself restyle established figures.

    if nargin < 1 || isempty(uiScale) || ~isfinite(uiScale)
        uiScale = 1;
    end
    uiScale = min(1.15,max(0.9,double(uiScale)));
    if nargin < 2 || isempty(screenWidth) || ~isfinite(screenWidth)
        screenWidth = 1920;
    end

    theme.scenarios.order = {'tt','te','et','ee'};
    theme.colors.scenario = struct( ...
        'tt',[0.00 0.25 1.00], ...
        'te',[1.00 0.65 0.00], ...
        'et',[0.65 0.00 0.85], ...
        'ee',[0.00 0.62 0.20]);
    theme.colors.scenarioMatrix = [ ...
        theme.colors.scenario.tt; theme.colors.scenario.te; ...
        theme.colors.scenario.et; theme.colors.scenario.ee];

    theme.colors.scenarioLight = struct( ...
        'tt',[0.6500 0.7375 1.0000], ...
        'te',[1.0000 0.8775 0.6500], ...
        'et',[0.8775 0.6500 0.9475], ...
        'ee',[0.6500 0.8670 0.7200]);
    theme.colors.scenarioLightMatrix = [ ...
        theme.colors.scenarioLight.tt; theme.colors.scenarioLight.te; ...
        theme.colors.scenarioLight.et; theme.colors.scenarioLight.ee];

    theme.colors.period = struct( ...
        'training',[0.204 0.471 0.831], ...
        'evaluation',[0.949 0.647 0.102], ...
        'gap',[0.94 0.94 0.94]);
    theme.colors.basin = struct( ...
        'training',theme.colors.scenario.tt, ...
        'evaluation',theme.colors.scenario.ee);
    theme.colors.neutral = struct( ...
        'black',[0 0 0], 'dark',[0.15 0.15 0.15], ...
        'axis',[0.18 0.18 0.18], ...
        'frame',[0.62 0.62 0.62], ...
        'grid',[0.84 0.84 0.84], ...
        'annotation',[0.38 0.38 0.38], ...
        'observation',[0.23 0.23 0.23], ...
        'trainingObserved',[0.25 0.25 0.25], ...
        'evaluationObserved',[0.55 0.55 0.55]);
    theme.colors.forcing = struct( ...
        'precipitation',[0 0 1], ...
        'potentialEvapotranspiration',[0.46 0.55 0.89], ...
        'temperatureBelowZero',[0 0 0]);
    theme.colors.shading = struct( ...
        'training',[0.94 0.94 0.94], ...
        'evaluation',[0.90 0.92 0.96]);

    % Model colors are independent of scenario and basin-membership
    % colors. Rows correspond to the public/internal model IDs below.
    theme.models.ids = [1:8 11 99];
    theme.colors.model = [ ...
        214/255  39/255  40/255; ...
         44/255 160/255  44/255; ...
        148/255 103/255 189/255; ...
        140/255  86/255  75/255; ...
         31/255 119/255 180/255; ...
        255/255 127/255  14/255; ...
        0.9000 0.0000 0.9000; ...
        0.0000 0.7000 0.7000; ...
        0.8500 0.3250 0.0980; ...
        0.4940 0.1840 0.5560];
    theme.colors.modelUnknown = [0.65 0.65 0.65];

    fonts = struct();
    fonts.dropdown = round(15*uiScale);
    fonts.preview = round(16*uiScale);
    fonts.gui = round(15*uiScale);
    fonts.slice = fonts.gui + 2.5;
    fonts.button = 15;
    if screenWidth >= 1800, fonts.button = 14; end
    fonts.path = fonts.gui;
    fonts.value = round(15*uiScale);
    fonts.table = round(14.5*uiScale);
    fonts.readiness = round(15*uiScale);
    fonts.checks = round(15*uiScale);
    fonts.iteration = round(16.5*uiScale);
    fonts.notes = round(15*uiScale);
    fonts.diagnosticTick = round(16*uiScale);
    fonts.diagnosticLabel = round(16*uiScale);
    fonts.diagnosticTitle = round(16*uiScale);
    fonts.diagnosticLegend = round(14.5*uiScale);
    fonts.diagnosticText = round(13.5*uiScale);
    theme.fonts.gui = fonts;

    % Semantic font families. GUI and report text must not inherit platform
    % defaults; scientific axes use one cross-surface publication family.
    theme.fonts.family = struct( ...
        'gui','Segoe UI', ...
        'scientific','Times New Roman', ...
        'monospace','Consolas', ...
        'document','Segoe UI');

    theme.lines = struct('axes',1,'data',1.4,'emphasis',2.25, ...
        'reference',0.9,'thin',0.5);
    theme.markers = struct('small',4,'standard',6,'large',9);
    theme.axes = struct('fontName','Times New Roman', ...
        'tickDirection','out','tickLength',[0.018 0.018], ...
        'background',[0.94 0.94 0.94]);
    theme.plots = struct( ...
        'fontName','Times New Roman', ...
        'titleSize',16,'labelSize',15,'tickSize',13, ...
        'annotationSize',12,'legendSize',13, ...
        'titleWeight','bold','labelWeight','bold', ...
        'axisColor',theme.colors.neutral.axis, ...
        'frameColor',theme.colors.neutral.frame, ...
        'gridColor',theme.colors.neutral.grid, ...
        'annotationColor',theme.colors.neutral.annotation, ...
        'observationColor',theme.colors.neutral.observation, ...
        'observationAlpha',0.58,'observationSize',8, ...
        'modelLineWidth',1.7,'precipitationLineWidth',0.05, ...
        'evapotranspirationLineWidth',1.05, ...
        'axisLineWidth',0.8,'frameLineWidth',0.55, ...
        'gridAlpha',0.24,'dateTickCount',5);
    theme.interpreters = struct( ...
        'ui','none','identifier','none','title','tex', ...
        'label','tex','annotation','tex','equation','latex', ...
        'tick','none');
    theme.legend = struct('box','off','location','best', ...
        'fontName',theme.fonts.family.scientific, ...
        'fontSize',theme.plots.legendSize, ...
        'textColor',theme.colors.neutral.dark);
    theme.colorbar = struct( ...
        'fontName',theme.fonts.family.scientific, ...
        'fontSize',theme.plots.tickSize, ...
        'color',theme.colors.neutral.axis, ...
        'lineWidth',theme.plots.frameLineWidth);
    theme.tables = struct( ...
        'fontName',theme.fonts.family.gui, ...
        'fontSize',fonts.table,'headerWeight','bold');
    theme.placeholders = struct( ...
        'fontName',theme.fonts.family.scientific, ...
        'fontSize',theme.plots.annotationSize, ...
        'fontWeight','normal', ...
        'color',theme.colors.neutral.annotation);
    theme.controls = struct('buttonHeight',28,'rowHeight',32);
    theme.backgrounds = struct( ...
        'gui',[0.94 0.94 0.94], ...
        'standalone',[1 1 1], ...
        'export',[1 1 1]);
    theme.status = struct( ...
        'success',[0.00 0.50 0.16], ...
        'warning',[0.88 0.53 0.00], ...
        'error',[0.78 0.10 0.10], ...
        'information',[0.10 0.36 0.72], ...
        'muted',theme.colors.neutral.annotation);
    theme.export = struct( ...
        'titleSize',28,'subtitleSize',20,'sectionSize',18, ...
        'bodySize',14,'noteSize',11,'tableSize',14, ...
        'fontName',theme.fonts.family.scientific, ...
        'titleWeight','bold','bodyWeight','normal');
    theme.profiles = struct( ...
        'gui',local_profile(1.00,'gui'), ...
        'compact',local_profile(0.90,'gui'), ...
        'standalone',local_profile(1.00,'standalone'), ...
        'publication',local_profile(1.08,'standalone'), ...
        'pptx',local_profile(1.12,'export'));
    theme.spacing = struct('compact',6,'standard',10,'comfortable',14);
end

function profile = local_profile(scale,background)
profile = struct('scale',scale,'background',background, ...
    'box','on','layer','top','gridDefault','off');
end
