function mdl = apply_parameter_override( ...
        mdl,parOverride,modelIdx,dt)
%APPLY_PARAMETER_OVERRIDE Apply GUI bounds for one model and resolution.

    if ~isstruct(mdl) ...
            || ~isfield(mdl,'th_min') ...
            || ~isfield(mdl,'th_max')
        error('apply_parameter_override:InvalidModel', ...
            'mdl must contain th_min and th_max.');
    end

    if ~(isnumeric(modelIdx) ...
            && isscalar(modelIdx) ...
            && isfinite(modelIdx) ...
            && modelIdx == fix(modelIdx))
        error('apply_parameter_override:InvalidModelIndex', ...
            'modelIdx must be a finite integer scalar.');
    end

    if ~(isnumeric(dt) ...
            && isscalar(dt) ...
            && isfinite(dt) ...
            && ismember(double(dt),[1 24 96]))
        error('apply_parameter_override:InvalidResolution', ...
            'dt must be 1, 24, or 96.');
    end

    % No saved overrides is a valid condition.
    if isempty(parOverride)
        return
    end

    if ~isstruct(parOverride) || ~isscalar(parOverride)
        error('apply_parameter_override:InvalidOverrides', ...
            'parOverride must be a scalar structure.');
    end

    key = sprintf('m%02d_dt%02d',modelIdx,dt);

    % No override for this model/resolution: retain defaults.
    if ~isfield(parOverride,key)
        return
    end

    O = parOverride.(key);

    if ~isstruct(O) || ~isscalar(O) ...
            || ~isfield(O,'min') ...
            || ~isfield(O,'max') ...
            || ~isfield(O,'names')
        error('apply_parameter_override:InvalidEntry', ...
            ['Override %s must contain names, ' ...
             'min, and max.'],key);
    end

    minOverride = double(O.min(:));
    maxOverride = double(O.max(:));

    nParameters = numel(mdl.th_min);

    if numel(mdl.th_max) ~= nParameters ...
            || numel(minOverride) ~= nParameters ...
            || numel(maxOverride) ~= nParameters
        error('apply_parameter_override:SizeMismatch', ...
            ['Saved parameter bounds do not match ' ...
             'the selected model.']);
    end

    if ~isfield(mdl,'par_names') ...
            || numel(mdl.par_names) ~= nParameters ...
            || ~isequal(string(O.names(:)), ...
                        string(mdl.par_names(:)))
        error('apply_parameter_override:NameMismatch', ...
            ['Saved parameter names do not match ' ...
             'the selected model.']);
    end

    if any(~isfinite(minOverride)) ...
            || any(~isfinite(maxOverride))
        error('apply_parameter_override:NonfiniteBounds', ...
            'Parameter bounds must be finite.');
    end

    invalid = minOverride >= maxOverride;

    if any(invalid)
        badNames = string(mdl.par_names(invalid));

        error('apply_parameter_override:InvalidBounds', ...
            ['Every lower bound must be smaller than its ' ...
             'upper bound. Invalid parameter(s): %s'], ...
            strjoin(badNames,', '));
    end

    % Preserve the orientation expected by the model implementation.
    mdl.th_min = reshape(minOverride,size(mdl.th_min));
    mdl.th_max = reshape(maxOverride,size(mdl.th_max));
end