function req = build_requested_window(split,include_spinup)
%BUILD_REQUESTED_WINDOW Build global file-read window from split

if nargin < 2 ...
        || isempty(include_spinup)
    include_spinup = false;
end

dt = double(split.dt);

switch dt
    case 1
        tref = datetime(1950,10,1,0,0,0);

        if include_spinup
            t0 = dateshift(split.dt0, ...
                'start','day');
        else
            t0 = min( ...
                dateshift(split.dt_train0, ...
                'start','day'), ...
                dateshift(split.dt_eval0, ...
                'start','day'));
        end

        t1 = max( ...
            dateshift(split.dt_train1, ...
            'start','day'), ...
            dateshift(split.dt_eval1, ...
            'start','day'));

        req.read_start_N = int64(days( ...
            t0 - dateshift(tref,'start','day')));
        req.read_end_N = int64(days( ...
            t1 - dateshift(tref,'start','day')));

    case 24
        tref = datetime(1950,10,1,0,0,0);

        if include_spinup
            t0 = datetime(year(split.dt0), ...
                month(split.dt0), ...
                day(split.dt0),0,0,0);
        else
            tTrain0 = datetime(year(split.dt_train0), ...
                month(split.dt_train0), ...
                day(split.dt_train0),0,0,0);
            tEval0  = datetime(year(split.dt_eval0), ...
                month(split.dt_eval0), ...
                day(split.dt_eval0),0,0,0);
            t0 = min(tTrain0,tEval0);
        end

        tTrain1 = datetime(year(split.dt_train1), ...
            month(split.dt_train1), ...
            day(split.dt_train1),23,0,0);
        tEval1 = datetime(year(split.dt_eval1), ...
            month(split.dt_eval1), ...
            day(split.dt_eval1),23,0,0);
        t1 = max(tTrain1,tEval1);

        req.read_start_N = int64(round(hours(t0 - tref)));
        req.read_end_N = int64(round(hours(t1 - tref)));

    case 96
        tref = datetime(1950,10,1,0,0,0);
        if include_spinup, t0 = dateshift(split.dt0,'start','day');
        else, t0 = min(dateshift(split.dt_train0,'start','day'), ...
                dateshift(split.dt_eval0,'start','day')); end
        t1 = max(dateshift(split.dt_train1,'start','day'), ...
            dateshift(split.dt_eval1,'start','day')) + hours(23) + minutes(45);
        req.read_start_N = int64(round(minutes(t0-tref)/15));
        req.read_end_N = int64(round(minutes(t1-tref)/15));

    otherwise
        error(['      Error:build_requested_window: ' ...
            'Unsupported dt = %d.'],dt);
end

end
