function split = prepare_split(split)
%PREPARE_SPLIT Validate split structure and build global indices if needed

if isempty(split) ...
        || ~isstruct(split)
    error(['      Error:prepare_split: ' ...
        'split structure is missing.']);
end

validateattributes(split.dt, ...
    {'numeric'},{'scalar','finite'});
validateattributes(split.mode, ...
    {'numeric'},{'scalar','finite','integer'});

if ~ismember(double(split.dt),[1 24 96])
    error(['      Error:prepare_split: ' ...
        'split.dt must be 1, 24, or 96.']);
end

req = {'dt','mode','dt0','dt_train0', ...
    'dt_train1','dt_eval0','dt_eval1', ...
    'dt_end'};
for i = 1:numel(req)
    if ~isfield(split,req{i}) ...
            || isempty(split.(req{i}))
        error(['      Error:prepare_split: ' ...
            'split.%s is missing.'],req{i});
    end
end

if ~isfield(split,'tout') ...
       || isempty(split.tout) ...
       || ~isfield(split,'idx') ...
       || isempty(split.idx) ...
       || ~isfield(split,'id_train') ...
       || isempty(split.id_train) ...
       || ~isfield(split,'id_eval') ...
       || isempty(split.id_eval)
    split = build_split_indices(split);
end

end