function info = information_bottleneck_SAGE(A,H,Y,opts)
%INFORMATION_BOTTLENECK_SAGE Native computational wrapper for SAGE.
%
%   info = information_bottleneck_SAGE(A,H,Y,opts)
%
% Numerical work is performed by information_bottleneck_SAGE_mex. This
% wrapper creates no figures. The SAGE GUI owns all visualization.
%
% Threading behavior
% ------------------
% If opts.info_threads is not supplied:
%   - on the MATLAB client: defaults to serial (1 thread) for safety
%   - inside a parallel worker: forced to serial (1 thread)
%
% Recommended:
%   opts.info_threads = 1;   % safest / serial
%   opts.info_threads = 4;   % explicit OpenMP parallelism
%   opts.info_threads = 0;   % automatic maximum OpenMP threads
%
% The master switch opts.info_parallel = false forces serial mode.

    if nargin < 4 ...
            || isempty(opts)
        opts = struct();
    end

    opts = local_defaults(opts);

    % Prevent nested parallelism by default inside MATLAB workers.
    if ~isfield(opts,'info_threads') ...
            || isempty(opts.info_threads)
        opts.info_threads = 1;   % force serial inside worker
    end

    if exist('information_bottleneck_SAGE_mex','file') ~= 3
        if exist('information_bottleneck_SAGE_matlab','file') == 2
            warning('SAGE:Information:MexUnavailable', ...
                ['information_bottleneck_SAGE_mex ' ...
                'is unavailable; using the ' ...
                 'MATLAB reference implementation.']);
            info = information_bottleneck_SAGE_matlab(A,H,Y,opts);
            return
        end

        error('SAGE:Information:MexUnavailable', ...
            ['information_bottleneck_SAGE_mex is unavailable. Run ' ...
             'compile_information in source ' ...
             'MATLAB or include the native ' ...
             'MEX in the deployed SAGE build.']);
    end

    info = information_bottleneck_SAGE_mex( ...
        double(A),H,double(Y),opts);
end


function opts = local_defaults(opts)

    D = struct( ...
        'nbins',10, ...
        'target_nbins',8, ...
        'quantization','quantile', ...
        'ksg',true, ...
        'ksg_k',5, ...
        'ksg_target_indices',1, ...
        'ksg_standardize',true, ...
        'ksg_jitter',1e-10, ...
        'ksg_permutation_n',0, ...
        'ksg_uncertainty_neurons',false, ...
        'ksg_uncertainty_target_indices',1, ...
        'random_seed',1729, ...
        'active_entropy_threshold',0.10, ...
        'info_threads',1, ...
        'info_parallel',true);

    fn = fieldnames(D);
    for i = 1:numel(fn)
        if ~isfield(opts,fn{i}) ...
                || isempty(opts.(fn{i}))
            opts.(fn{i}) = D.(fn{i});
        end
    end
end
