function states = model_states(mdl,Z,requested,nq)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%MODEL_STATES Return named physical states on the discharge grid.
%
%  Extract physical states from augmented solver history, excluding
%  cumulative-discharge bookkeeping states.
%
% SYNOPSIS:
%   states = model_states(mdl,Z,requested,nq)
%
% INPUT ARGUMENTS:
%   mdl             model and output-time definition
%    .model          model identifier
%    .idx            indices of the discharge output grid
%    .y0             initial states for fixed-state models
%    .state_name     optional names for private or user models
%    .state_units    optional units for private or user models
%   Z               augmented state and sensitivity history
%   requested       "all" or a string/cell list of state names
%   nq              required number of output samples
%
% OUTPUT ARGUMENTS:
%   states          requested physical-state trajectories and metadata
%    .values         nq-by-n matrix of state trajectories
%    .names          n-by-1 state-name strings
%    .units          n-by-1 state-unit strings
%
% NOTES:
%   Rows of states.values are sampled using mdl.idx and must match the
%   discharge trajectory length nq.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    if ismember(mdl.model,[11 99])
        % A user model can have a parameter-dependent number
        % of routing-memory states known only after solver preparation.
        d = numel(mdl.th_min);
        m = size(Z,2)/(d+1);
        if m ~= fix(m)
            error('model_states:InvalidAugmentedHistory', ...
                ['Cannot infer the physical-state ' ...
                'count from the solver history.']);
        end
        nstate = m - 1;
    else
        nstate = numel(mdl.y0) - 1;
    end
    [names,units] = local_catalog(mdl,nstate);
    if isempty(Z) ...
            || size(Z,2) < nstate
        error('model_states:Unavailable', ...
            ['The selected model did not ' ...
            'return its state history.']);
    end
    values = Z(mdl.idx(1)+1:mdl.idx(2),1:nstate);
    if size(values,1) ~= nq
        error('model_states:LengthMismatch', ...
            ['State and discharge histories ' ...
            'have different lengths.']);
    end
    if ~(isscalar(requested) ...
            && strcmpi(requested,"all"))
        [tf,loc] = ismember(lower(requested), ...
            lower(names));
        if ~all(tf)
            error('model_states:UnknownState', ...
                'Unknown state(s): %s.', ...
                strjoin(requested(~tf),', '));
        end
        names = names(loc); 
        units = units(loc); 
        values = values(:,loc);
    end
    states = struct('values',values, ...
        'names',names, ...
        'units',units);
end

function [names,units] = local_catalog(mdl,nstate)
%LOCAL_CATALOG Return state names and units for the selected model.

    switch mdl.model
        case 1
            names = ["snow_water_equivalent", ...
                "soil_storage", ...
                "slow_reservoir", ...
                "fast_reservoir_1", ...
                "fast_reservoir_2", ...
                "fast_reservoir_3"];
        case 2
            names = ["snow_water_equivalent", ...
                "interception_storage", ...
                "soil_storage", ...
                "fast_reservoir", ...
                "slow_reservoir"];
        case 3
            names = ["snow_water_equivalent", ...
                "upper_tension_water", ...
                "upper_free_water", ...
                "lower_tension_water", ...
                "lower_primary_free_water", ...
                "lower_supplemental_free_water", ...
                "routing_reservoir_1", ...
                "routing_reservoir_2", ...
                "routing_reservoir_3"];
        case 4
            names = ["snow_water_equivalent", ...
                "tension_water", ...
                "free_water", ...
                "interflow_reservoir", ...
                "baseflow_reservoir", ...
                "routing_reservoir_1", ...
                "routing_reservoir_2", ...
                "routing_reservoir_3"];
        case 5
            n = nstate - 3;
            names = ["snow_water_equivalent", ...
                "production_store", ...
                "routing_store", ...
                compose("unit_hydrograph_storage_%d",1:n)];
        case 6
            names = ["snow_water_equivalent", ...
                "soil_moisture", ...
                "upper_zone", ...
                "lower_zone"];
        case 7
            n = nstate - 3;
            names = ["snow_water_equivalent", ...
                "soil_storage", ...
                "groundwater_storage", ...
                compose("routing_storage_%d",1:n)];
        case 11
            if isfield(mdl,'state_name')
                names = string(mdl.state_name(1:nstate));
            else
                names = compose("state_%d",1:nstate);
            end
        case 99
            if isfield(mdl,'state_name')
                names = string(mdl.state_name(:))';
            else
                names = compose("state_%d",1:nstate);
            end
        otherwise
            error('model_states:UnknownModel', ...
                'Unknown model code %g.',mdl.model);
    end
    names = string(names(:)); 
    units = repmat("mm",nstate,1);
    if mdl.model == 11 && isfield(mdl,'state_units')
        units = string(mdl.state_units(1:nstate));
    end
    expected = nstate;
    if numel(names) ~= expected
        error('model_states:CatalogMismatch', ...
            ['State catalog has %d names ' ...
            'but model has %d physical states.'], ...
            numel(names),expected);
    end
end
